/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductRotrackerImport } from './routes/product/rotracker'
import { Route as ProductQuickfinderImport } from './routes/product/quickfinder'
import { Route as ProductFlowImport } from './routes/product/flow'
import { Route as ProductConversioImport } from './routes/product/conversio'
import { Route as ProductSlugImport } from './routes/product/$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductRotrackerRoute = ProductRotrackerImport.update({
  id: '/product/rotracker',
  path: '/product/rotracker',
  getParentRoute: () => rootRoute,
} as any)

const ProductQuickfinderRoute = ProductQuickfinderImport.update({
  id: '/product/quickfinder',
  path: '/product/quickfinder',
  getParentRoute: () => rootRoute,
} as any)

const ProductFlowRoute = ProductFlowImport.update({
  id: '/product/flow',
  path: '/product/flow',
  getParentRoute: () => rootRoute,
} as any)

const ProductConversioRoute = ProductConversioImport.update({
  id: '/product/conversio',
  path: '/product/conversio',
  getParentRoute: () => rootRoute,
} as any)

const ProductSlugRoute = ProductSlugImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugImport
      parentRoute: typeof rootRoute
    }
    '/product/conversio': {
      id: '/product/conversio'
      path: '/product/conversio'
      fullPath: '/product/conversio'
      preLoaderRoute: typeof ProductConversioImport
      parentRoute: typeof rootRoute
    }
    '/product/flow': {
      id: '/product/flow'
      path: '/product/flow'
      fullPath: '/product/flow'
      preLoaderRoute: typeof ProductFlowImport
      parentRoute: typeof rootRoute
    }
    '/product/quickfinder': {
      id: '/product/quickfinder'
      path: '/product/quickfinder'
      fullPath: '/product/quickfinder'
      preLoaderRoute: typeof ProductQuickfinderImport
      parentRoute: typeof rootRoute
    }
    '/product/rotracker': {
      id: '/product/rotracker'
      path: '/product/rotracker'
      fullPath: '/product/rotracker'
      preLoaderRoute: typeof ProductRotrackerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  id:
    | '__root__'
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductConversioRoute: typeof ProductConversioRoute
  ProductFlowRoute: typeof ProductFlowRoute
  ProductQuickfinderRoute: typeof ProductQuickfinderRoute
  ProductRotrackerRoute: typeof ProductRotrackerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductConversioRoute: ProductConversioRoute,
  ProductFlowRoute: ProductFlowRoute,
  ProductQuickfinderRoute: ProductQuickfinderRoute,
  ProductRotrackerRoute: ProductRotrackerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product/$slug",
        "/product/conversio",
        "/product/flow",
        "/product/quickfinder",
        "/product/rotracker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/product/$slug": {
      "filePath": "product/$slug.tsx"
    },
    "/product/conversio": {
      "filePath": "product/conversio.tsx"
    },
    "/product/flow": {
      "filePath": "product/flow.tsx"
    },
    "/product/quickfinder": {
      "filePath": "product/quickfinder.tsx"
    },
    "/product/rotracker": {
      "filePath": "product/rotracker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
