/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductRotrackerRouteImport } from './routes/product/rotracker'
import { Route as ProductQuickfinderRouteImport } from './routes/product/quickfinder'
import { Route as ProductFlowRouteImport } from './routes/product/flow'
import { Route as ProductConversioRouteImport } from './routes/product/conversio'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRotrackerRoute = ProductRotrackerRouteImport.update({
  id: '/product/rotracker',
  path: '/product/rotracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductQuickfinderRoute = ProductQuickfinderRouteImport.update({
  id: '/product/quickfinder',
  path: '/product/quickfinder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductFlowRoute = ProductFlowRouteImport.update({
  id: '/product/flow',
  path: '/product/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductConversioRoute = ProductConversioRouteImport.update({
  id: '/product/conversio',
  path: '/product/conversio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/conversio': typeof ProductConversioRoute
  '/product/flow': typeof ProductFlowRoute
  '/product/quickfinder': typeof ProductQuickfinderRoute
  '/product/rotracker': typeof ProductRotrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  id:
    | '__root__'
    | '/'
    | '/product/$slug'
    | '/product/conversio'
    | '/product/flow'
    | '/product/quickfinder'
    | '/product/rotracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductConversioRoute: typeof ProductConversioRoute
  ProductFlowRoute: typeof ProductFlowRoute
  ProductQuickfinderRoute: typeof ProductQuickfinderRoute
  ProductRotrackerRoute: typeof ProductRotrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/rotracker': {
      id: '/product/rotracker'
      path: '/product/rotracker'
      fullPath: '/product/rotracker'
      preLoaderRoute: typeof ProductRotrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/quickfinder': {
      id: '/product/quickfinder'
      path: '/product/quickfinder'
      fullPath: '/product/quickfinder'
      preLoaderRoute: typeof ProductQuickfinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/flow': {
      id: '/product/flow'
      path: '/product/flow'
      fullPath: '/product/flow'
      preLoaderRoute: typeof ProductFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/conversio': {
      id: '/product/conversio'
      path: '/product/conversio'
      fullPath: '/product/conversio'
      preLoaderRoute: typeof ProductConversioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductConversioRoute: ProductConversioRoute,
  ProductFlowRoute: ProductFlowRoute,
  ProductQuickfinderRoute: ProductQuickfinderRoute,
  ProductRotrackerRoute: ProductRotrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
